### ISSUE TITLE
make dirties source repo

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/spec#248]
When the spec repo was used with make, and then `git pull` is performed, it looks like make leaves behind dirty files which prevent `git pull` from succeeding:
```
subprocess.check_call(`git checkout origin/master`, cwd=`/b/build/slave/linux/build/src/src/work/spec`)
error: Your local changes to the following files would be overwritten by checkout:
	ml-proto/winmake.bat
Please, commit your changes or stash them before you can switch branches.
Aborting
Traceback (most recent call last):
  File "/b/build/slave/linux/build/src/src/build.py", line 722, in <module>
    sys.exit(main(options.sync, options.build))
  File "/b/build/slave/linux/build/src/src/build.py", line 657, in main
    SyncRepos()
  File "/b/build/slave/linux/build/src/src/build.py", line 409, in SyncRepos
    repo.Sync()
  File "/b/build/slave/linux/build/src/src/build.py", line 258, in Sync
    self.GitCloneFetchCheckout()
  File "/b/build/slave/linux/build/src/src/build.py", line 274, in GitCloneFetchCheckout
    proc.check_call(['git', 'checkout', self.checkout], cwd=self.src_dir)
  File "/b/build/slave/linux/build/src/src/proc.py", line 36, in check_call
    return subprocess.check_call(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'checkout', 'origin/master']' returned non-zero exit status 1
```

**Comment by rossberg-chromium** [comment]
Should be fixed by #254.
